apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-
spec:
  pipelineRef:
    name: build
  serviceAccountName: pipeline
  params:
  - name: git-url
    value: https://github.com/aushacker/mynorthwind.git
  - name: image
    value: 'image-registry.openshift-image-registry.svc:5000/mynorthwind/mynorthwind'
  - name: context
    value: dockerdb
  workspaces:
  - name: data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: '500Mi'
  - name: maven-settings
    configMap:
      name: custom-maven-settings
