apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: git-assemble
spec:
  params:
  - name: git-url
    value: $(body.repository.url)
  - name: git-revision
    value: $(body.head_commit.id)

