---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nw-db
  labels:
    app.openshift.io/runtime: mysql-database
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: nw-db
  template:
    metadata:
      labels:
        deployment: nw-db
    spec:
      containers:
      - image: 'image-registry.openshift-image-registry.svc:5000/mynorthwind/mynorthwind'
        name: northwind
        env:
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: nwconfig
                key: MYSQL_USER
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: nwconfig
                key: MYSQL_DATABASE
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbpw
                key: MYSQL_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbpw
                key: MYSQL_ROOT_PASSWORD
        ports:
          - containerPort: 3306
            protocol: TCP
          - containerPort: 33060
            protocol: TCP

