#---
#apiVersion: image.openshift.io/v1
#kind: ImageStream
#metadata:
#  name: northwinddb
#  labels:
#    app: nwdb
#spec:
#  tags:
#  - name: '1.0'
#    from:
#      kind: DockerImage
#      name: 'quay.io/sdavies/mynorthwind:1.0'
#    generation: 1
#    referencePolicy:
#      type: Source
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nwconfig
  labels:
    app: nwdb
data:
  MYSQL_USER: test1
  MYSQL_DATABASE: northwind
---
apiVersion: v1
kind: Secret
metadata:
  name: dbpw
  labels:
    app: nwdb
stringData:
  MYSQL_PASSWORD: mypa55
  MYSQL_ROOT_PASSWORD: r00tpa55
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwdb
  labels:
    app: nwdb
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: nwdb
  template:
    metadata:
      labels:
        deployment: nwdb
    spec:
      containers:
      - image: quay.io/sdavies/mynorthwind:1.0
        name: northwind
        env:
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: nwconfig
                key: MYSQL_USER
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: nwconfig
                key: MYSQL_DATABASE
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbpw
                key: MYSQL_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbpw
                key: MYSQL_ROOT_PASSWORD
        ports:
          - containerPort: 3306
            protocol: TCP
          - containerPort: 33060
            protocol: TCP

