kind: Service
apiVersion: v1
metadata:
  name: nw-db
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
#  - protocol: TCP
#    port: 33060
#    targetPort: 33060
  selector:
    deployment: nw-db
