---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-datasource
data:
  DB_SERVICE_PREFIX_MAPPING: northwind-mysql=DS1
  NORTHWIND_MYSQL_SERVICE_HOST: nw-db
  NORTHWIND_MYSQL_SERVICE_PORT: '3306'
  DS1_JNDI: java:/NorthwindDS
  DS1_DATABASE: northwind
  DS1_NONXA: 'true'
  DS1_MIN_POOL_SIZE: '20'
  DS1_MAX_POOL_SIZE: '20'
  DS1_CONNECTION_CHECKER: org.jboss.jca.adapters.jdbc.extensions.mysql.MySQLValidConnectionChecker
  DS1_EXCEPTION_SORTER: org.jboss.jca.adapters.jdbc.extensions.mysql.MySQLExceptionSorter
