---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nw-web
  labels:
    app.openshift.io/runtime: eap
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: nw-web
  template:
    metadata:
      labels:
        deployment: nw-web
    spec:
      containers:
      - image: northwind-app
        name: nw-web
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: nwconfig
                key: MYSQL_DATABASE
          - name: DS1_USERNAME
            valueFrom:
              configMapKeyRef:
                name: nwconfig
                key: MYSQL_USER
          - name: DS1_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbpw
                key: MYSQL_PASSWORD
        envFrom:
        - configMapRef:
            name: web-datasource
        ports:
          - containerPort: 8080
