apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git-assemble
spec:
  workspaces:
  - name: ssh-creds
  - name: data
  params:
  -
    name: git-url
    type: string
    description: git repo url
  -
    name: git-revision
    type: string
    description: "branch, tag, sha etc."
    default: master
  -
    name: git-subdir
    type: string
    description: git subdirectory
    default: ""
  -
    name: context
    type: string
    description: context path to Dockerfile
    default: ""
  -
    name: image
    type: string
    description: buildah output image name
  tasks:
  -
    name: git-fetch
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: data
    - name: ssh-directory
      workspace: ssh-creds
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.git-revision)
    - name: subdirectory
      value: $(params.git-subdir)
    - name: sslVerify
      value: 'false'
  -
    name: buildah-assembly
    taskRef:
      name: buildah
      kind: ClusterTask
    workspaces:
    - name: source
      workspace: data
    params:
    - name: IMAGE
      value: $(params.image)
    - name: CONTEXT
      value: $(params.context)
    runAfter:
    - git-fetch
