apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git-assemble
spec:
  params:
  -
    name: git-url
    type: string
    description: git repo url
  -
    name: git-revision
    type: string
    description: "branch, tag, sha etc."
    default: master
  -
    name: git-subdir
    type: string
    description: git subdirectory
    default: ""
  -
    name: context
    type: string
    description: context path to Dockerfile
    default: ""
  -
    name: image
    type: string
    description: buildah output image name

  workspaces:
  - name: ssh-creds
  - name: data
  - name: maven-settings

  tasks:
  -
    name: git-fetch
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
    -
      name: url
      value: $(params.git-url)
    -
      name: revision
      value: $(params.git-revision)
    -
      name: subdirectory
      value: $(params.git-subdir)
    -
      name: sslVerify
      value: 'false'
    workspaces:
    -
      name: output
      workspace: data
    -
      name: ssh-directory
      workspace: ssh-creds
  -
    name: build-database-image
    taskRef:
      name: buildah
      kind: ClusterTask
    runAfter:
    - git-fetch
    params:
    - name: IMAGE
      value: $(params.image)
    - name: CONTEXT
      value: $(params.context)
    workspaces:
    - name: source
      workspace: data
  -
    name: maven-jpa
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
    - git-fetch
    params:
    -
      name: CONTEXT_DIR
      value: javadb
    -
      name: GOALS
      value:
      - --batch-mode
      - -DskipTests
      - clean
      - package
    workspaces:
    - name: source
      workspace: data
    - name: maven-settings
      workspace: maven-settings
