apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: run-git-assemble-
spec:
  pipelineRef:
    name: git-assemble
  serviceAccountName: pipeline
  params:
  - name: git-url
    value: ssh://sjdavies@maximin/data1/git/mynorthwind.git
  - name: image
    value: image-registry.openshift-image-registry.svc:5000/test1/mynorthwind
  - name: context
    value: dockerdb
  workspaces:
  - name: ssh-creds
    secret:
      secretName: ssh-sjd
  - name: data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
  - name: maven-settings
    configMap:
      name: custom-maven-settings
